/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 46cb16d3afacd579def2569505459731)
interface __BaseEnv_Env {
	MARKET_CACHE: KVNamespace;
	ASSETS: Fetcher;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	MARKET_AUTH_REQUIRED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
